In [1]:
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import os
from pathlib import Path

PROJECT_ROOT = Path(os.environ["PROJECT_ROOT"])
from auxiliary.static_data import *
from auxiliary.auxiliary_funcs import *

df_test = pd.read_csv("test.csv")
df_sample_submission = pd.read_csv("sample_submission.csv")
df_city_indexes = pd.read_csv(os.path.join(PROJECT_ROOT, "train", "city_indexes.csv"))
df_city_search_index = pd.read_csv(
    os.path.join(PROJECT_ROOT, "train", "city_search_index.csv")
)

pd.set_option("display.max_columns", 80)

In [2]:
df_city_indexes

,city_indicator_data_year,year_end_registered_population_10k,total_households_10k,year_end_resident_population_10k,year_end_total_employed_population_10k,year_end_urban_non_private_employees_10k,private_individual_and_other_employees_10k,private_individual_ratio,national_year_end_total_population_10k,resident_registered_ratio,under_18_10k,18_60_years_10k,over_60_years_10k,total,under_18_percent,18_60_years_percent,over_60_years_percent,gdp_100m,primary_industry_100m,secondary_industry_100m,tertiary_industry_100m,gdp_per_capita_yuan,national_gdp_100m,national_economic_primacy,national_population_share,gdp_population_ratio,secondary_industry_development_gdp_share,tertiary_industry_development_gdp_share,employed_population,primary_industry_percent,secondary_industry_percent,tertiary_industry_percent,white_collar_service_vs_blue_collar_manufacturing_ratio,general_public_budget_revenue_100m,personal_income_tax_100m,per_capita_personal_income_tax_yuan,general_public_budget_expenditure_100m,total_retail_sales_of_consumer_goods_100m,retail_sales_growth_rate,urban_consumer_price_index_previous_year_100,annual_average_wage_urban_non_private_employees_yuan,annual_average_wage_urban_non_private_on_duty_employees_yuan,per_capita_disposable_income_absolute_yuan,per_capita_disposable_income_index_previous_year_100,engel_coefficient,per_capita_housing_area_sqm,number_of_universities,university_students_10k,number_of_middle_schools,middle_school_students_10k,number_of_primary_schools,primary_school_students_10k,number_of_kindergartens,kindergarten_students_10k,hospitals_health_centers,hospital_beds_10k,health_technical_personnel_10k,doctors_10k,road_length_km,road_area_10k_sqm,per_capita_urban_road_area_sqm,number_of_operating_bus_lines,operating_bus_line_length_km,internet_broadband_access_subscribers_10k,internet_broadband_access_ratio,number_of_industrial_enterprises_above_designated_size,total_current_assets_10k,total_fixed_assets_10k,main_business_taxes_and_surcharges_10k,total_fixed_asset_investment_10k,real_estate_development_investment_completed_10k,residential_development_investment_completed_10k,science_expenditure_10k,education_expenditure_10k
0,2017,897.87,295.0211,1449.84,862.33,329.17,708.0004,0.821032,139008,1.614755,171.4642,564.5623,161.8452,897.8717,0.190967,0.628778,0.180254,21503.15,220.45,6011.01,15271.69,150678,827122.0,0.025998,0.010430,2.492598,0.004561,0.075267,1037.17,0.0607,0.2481,0.6912,2.785973,1536.74,91.2142,1615.662257,2186.01,9402.59,0.079952,102.3,97522,98612,55400.49,108.8,32.1,33.07,82,106.73,518,50.94,961,100.47,1775,48.3497,4058,8.17,14.50,4.97,7819.31,13012.82,10.98,14,398,521.52,0.580841,4664,96779199,39013240.0,4012517.0,NaN,27028935.0,17694861.0,1712569.0,4043335.0
1,2018,927.69,305.9851,1490.44,1102.36,348.65,753.7146,0.683728,139538,1.606614,185.4274,572.9948,169.2692,927.6914,0.199880,0.617657,0.182463,21002.44,229.18,6109.95,14663.31,142860,919281.0,0.022847,0.010681,2.138944,0.004711,-0.028967,1102.36,0.0556,0.2391,0.7053,2.949812,1634.22,104.4782,1823.370823,2506.18,8810.91,-0.062927,102.4,109879,111839,59982.10,108.3,32.1,34.22,82,108.64,527,51.44,965,105.85,1846,49.8127,4598,8.60,15.65,5.41,14007.14,18742.99,14.25,16,485,544.17,0.586586,4675,99067099,NaN,4297060.0,NaN,27019323.0,17466618.0,1636655.0,4408209.0
2,2019,953.72,313.8455,1530.59,1125.89,400.22,725.6720,0.644532,140005,1.604863,197.7291,580.4792,175.5074,953.7157,0.207325,0.608650,0.184025,23628.60,251.37,6454.00,16923.23,156427,986515.0,0.023952,0.010932,2.190882,0.014561,0.095643,1125.89,0.0561,0.2272,0.7167,3.154489,1699.04,74.2215,1278.624626,2865.33,9551.57,0.084062,103.0,119453,123498,65052.10,108.5,32.0,34.37,81,114.09,534,52.62,980,110.47,1966,52.7648,5093,9.09,16.81,5.87,14083.44,18792.69,12.46,15,523,565.83,0.593287,5804,110643480,39934058.0,4862051.0,NaN,31022573.0,20870742.0,2439456.0,5239743.0
3,2020,985.11,322.1068,1874.03,1158.01,419.36,738.6462,0.637858,141212,1.902356,212.6908,592.4766,179.9468,985.1142,0.215905,0.601429,0.182666,25068.75,286.27,6716.16,18066.32,135315,1013567.0,0.024733,0.013271,1.863697,0.010458,0.045598,1158.01,0.0512,0.2243,0.7245,3.230049,1722.79,79.3333,1339.011532,2952.65,9218.66,-0.034854,102.6,130110,135138,68304.10,105.0,32.4,34.61,82,130.71,539,54.32,992,112.51,2068,57.4541,5550,9.31,17.78,6.23,14162.84,19147.09,12.51,16,553,619.78,0.629148,6208,123664111,NaN,NaN,NaN,NaN,NaN,2241321.0,5585916.0
4,2021,1011.53,329.7224,1881.06,1163.44,426.94,736.5017,0.633038,141260,1.859619,223.9536,602.7577,184.8193,1011.5306,0.221401,0.595887,0.182713,28225.21,299.75,7736.13,20189.34,150330,1149237.0,0.024560,0.013316,1.844353,0.036137,0.075217,1163.44,0.0501,0.2267,0.7232,3.190119,1884.26,95.8567,1590.302372,3021.18,10122.56,0.098051,101.1,139802,144288,74416.17,108.9,31.7,34.28,83,141.26,551,56.96,986,116.44,2155,63.3203,5814,9.71,18.77,6.62,14871.09,22242.95,11.83,17,611,694.68,0.686762,6757,142064810,NaN,NaN,NaN,NaN,NaN,2012478.0,5890857.0
5,2022,1034.91,336.1935,1873.41,1119.82,424.90,694.9159,0.620560,141175,1.810215,233.3934,606.3080,195.2060,1034.9074,0.225521,0.585857,0.188622,28839.00,318.31,7909.29,20611.40,153625,1210207.2,0.023830,0.013270,1.795748,0.006004,0.014635,1119.82,0.0418,0.2283,0.7299,3.197109,1855.10,102.7994,1695.497998,3022.45,10298.15,0.017346,102.4,147947,152324,76849.41,103.3,32.0,34.30,84,148.93,555,60.24,992,120.42,2223,65.5288,6159,10.05,19.57,6.87,14976.00,22411.16,11.96,18,643,762.52,0.736798,6878,159482630,NaN,NaN,NaN,NaN,NaN,1982136.0,6269391.0
6,2022,1034.91,336.1935,1873.41,1119.82,424.90,694.9159,0.620560,141175,1.810215,233.3934,606.3080,195.2060,1034.9074,0.225521,0.585857,0.188622,28839.00,318.31,7909.29,20611.40,153625,1210207.2,0.023830,0.013270,1.795748,0.006004,0.014635,1119.82,0.0418,0.2283,0.7299,3.197109,1855.10,102.7994,1695.497998,3022.45,10298.15,0.017346,102.4,147947,152324,76849.41,103.3,32.0,34.30,84,148.93,555,60.24,992,120.42,2223,65.5288,6159,10.05,19.57,6.87,14976.00,22411.16,11.96,18,643,762.52,0.736798,6878,159482630,NaN,NaN,NaN,NaN,NaN,NaN,NaN

All the data is from 2022 or before, but we want to make a prediction for 2024 and beyond. Hence, there's no point in using this data

In [3]:
df_city_search_index

         month keyword source  search_volume
0     2019-Jan      买房    PC端           1914
1     2019-Jan      买房    移动端           2646
2     2019-Jan   二手房市场    PC端            192
3     2019-Jan   二手房市场    移动端            204
4     2019-Jan     公积金    PC端           9160
...        ...     ...    ...            ...
4015  2024-Jul      限售    移动端             40
4016  2024-Jul      限购    PC端            203
4017  2024-Jul      限购    移动端            155
4018  2024-Jul      首付    PC端            739
4019  2024-Jul      首付    移动端           1471

[4020 rows x 4 columns]

ideas to use this: make an average, or pick the source that is most relevant